server:
  port: 8080
spring:
  # MySQL
  datasource:
    url: jdbc:mysql://localhost:13306/daejangjangi?useSSL=false&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
  # JPA
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
      data-locations: classpath:init.sql
  
  data:
    # REDIS
    redis:
      host: localhost
      port: 6379

    # MONGO
    mongodb:
      uri: mongodb://localhost:27017/test
