server:
  port: 8080

spring:
  application:
    name: Daejangjangi
  datasource:
    url: jdbc:mysql://mysql:3306/daejangjangi?useSSL=false&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${datasource.dev.usernames}
    password: ${datasource.dev.password}
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
      data-locations: classpath:init.sql
  data:
    redis:
      host: redis
      port: 6379
    mongodb:
      uri: mongodb://mongo:27017/daejangjangi