spring:
  profiles:
    active: local
  config:
    import: classpath:application-secret.yml

springdoc:
  swagger-ui:
    path: /api/swagger
    groups-order: DESC
    tags-sorter: alpha
    operations-sorter: method
    disable-swagger-default-url: true
    display-request-duration: true
    doc-expansion: false
  api-docs:
    path: /api-docs
  show-actuator: false
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  writer-with-default-pretty-printer: true
  override-with-generic-response: false  # 사용하지 않는 response 지우기
  paths-to-match:
    - /**