name: Build & Test

on:
  push:
    branches:
      - feat/*

jobs:
  gradle:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Create application-secret.yml
        run: |
          mkdir -p src/main/resources
          echo "${{secrets.SECRET_YML}}" | base64 --decode > src/main/resources/application-secret.yml

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build and test with gradle
        run: ./gradlew clean build

      - name: slack-notification
        uses: 8398a7/action-slack@v3
        with:
          status: ${{job.status}}
          author_name: Github Action Test
          fields: repo, message, commit, author, action, eventName, ref, workflow, job, took
        env:
          SLACK_WEBHOOK_URL: ${{secrets.SLACK_WEBHOOK_URL}}
        if: always()